import { createContext, useContext, useState } from "react";
import { Globe } from "lucide-react";

export type Language = "fr" | "ar";

export interface Translation {
  [key: string]: string;
}

export interface Translations {
  fr: Translation;
  ar: Translation;
}

export const translations: Translations = {
  fr: {
    securitySolutions: "Des solutions de sécurité pour tous",
    services: "Services",
    securityAudit: "Audit de sécurité",
    antivirusProtection: "Protection antivirus",
    secureBackup: "Sauvegarde sécurisée",
    wifiSecurity: "Sécurité Wifi",
    trainingAwareness: "Formation et sensibilisation",
    resources: "Ressources",
    guidesAndDocs: "Guides et documentation",
    caseStudies: "Études de cas",
    contact: "Contact",
    legalMentions: "Mentions légales",
    privacyPolicy: "Politique de confidentialité",
    copyright: "Tous droits réservés",
    home: "Accueil",
    pricing: "Tarification",
    aboutUs: "À propos de nous",
    whyUs: "Pourquoi nous choisir",
    ourValues: "Nos valeurs",
    ourMission: "Notre mission",
    ourVision: "Notre vision",
    contactUs: "Contactez-nous",
    getInTouch: "Restons en contact !",
    fullName: "Nom complet",
    email: "E-mail",
    phone: "Téléphone",
    message: "Message",
    sendMessage: "Envoyer le message",
    enterFullName: "Entrez votre nom complet",
    enterValidEmail: "Entrez une adresse e-mail valide",
    enterPhoneNumber: "Entrez votre numéro de téléphone",
    writeYourMessage: "Écrivez votre message",
    successMessage: "Votre message a été envoyé avec succès !",
    errorMessage: "Une erreur s'est produite. Veuillez réessayer.",
    latestNews: "Dernières nouvelles",
    readMore: "En savoir plus",
    stayUpdated: "Restez informé",
    subscribeToNewsletter: "Abonnez-vous à notre newsletter",
    enterYourEmail: "Entrez votre e-mail",
    subscribe: "S'abonner",
    subscribeSuccess: "Merci de vous être abonné à notre newsletter !",
    subscribeError: "Impossible de s'abonner. Veuillez réessayer.",
    highQualityServices: "Services de haute qualité",
    customerSatisfaction: "Satisfaction client",
    innovativeSolutions: "Solutions innovantes",
    expertTeam: "Équipe d'experts",
    yearsOfExperience: "Années d'expérience",
    happyClients: "Clients satisfaits",
    projectsCompleted: "Projets réalisés",
    ourPricing: "Nos tarifs",
    basicPlan: "Plan de base",
    standardPlan: "Plan standard",
    premiumPlan: "Plan premium",
    monthly: "par mois",
    annual: "par an",
    choosePlan: "Choisir ce plan",
    allRightsReserved: "Tous droits réservés",
    comprehensiveSecurity: "Sécurité complète pour votre entreprise",
    dataProtection: "Protection des données",
    networkSecurity: "Sécurité réseau",
    endpointSecurity: "Sécurité des terminaux",
    cloudSecurity: "Sécurité cloud",
    incidentResponse: "Réponse aux incidents",
    managedSecurityServices: "Services de sécurité gérés",
    vulnerabilityAssessment: "Évaluation des vulnérabilités",
    penetrationTesting: "Tests d'intrusion",
    securityConsulting: "Consulting en sécurité",
    complianceServices: "Services de conformité",
    digitalForensics: "Informatique légale",
    securityTraining: "Formation en sécurité",
    awarenessPrograms: "Programmes de sensibilisation",
    phishingSimulations: "Simulations de phishing",
    customTraining: "Formation personnalisée",
    ourClients: "Nos clients",
    testimonials: "Témoignages",
    whatPeopleSay: "Ce que les gens disent",
    submit: "Envoyer",
    firstName: "Prénom",
    lastName: "Nom",
    company: "Entreprise",
    function: "Fonction",
    enterFirstName: "Entrez votre prénom",
    enterLastName: "Entrez votre nom",
    enterCompanyName: "Entrez le nom de votre entreprise",
    enterYourFunction: "Entrez votre fonction",
    selectLanguage: "Sélectionner la langue",
    french: "Français",
    arabic: "Arabe",
    english: "Anglais",
    contactFormTitle: "Contactez-nous pour une consultation gratuite",
    contactFormDescription: "Remplissez le formulaire ci-dessous et nous vous contacterons dans les plus brefs délais.",
    address: "Adresse",
    phoneNumbers: "Numéros de téléphone",
    emailAddress: "Adresse e-mail",
    followUs: "Suivez-nous",
    ourOffices: "Nos bureaux",
    casablancaOffice: "Casablanca",
    rabatOffice: "Rabat",
    marrakechOffice: "Marrakech",
    ourPartners: "Nos partenaires",
    strategicAlliances: "Alliances stratégiques",
    technologyPartners: "Partenaires technologiques",
    industryAssociations: "Associations industrielles",
    ourBlog: "Notre blog",
    recentArticles: "Articles récents",
    whyChoose: "Pourquoi nous choisir",
    
    // Pricing page specific translations
    pricingTitle: "Nos forfaits et tarifs",
    pricingDescription: "Des solutions de sécurité adaptées à tous les budgets et besoins spécifiques",
    subscriptionPlansTitle: "Forfaits d'abonnement",
    servicesTitle: "Services ponctuels",
    servicesDescription: "Besoin d'une intervention ou d'une analyse ponctuelle? Découvrez nos services à la carte",
    paymentOptionsTitle: "Options de paiement",
    monthlyPayment: "Paiement mensuel",
    monthlyPaymentDesc: "Flexibilité maximale, sans engagement de durée",
    standardRate: "Tarif standard",
    yearlyPayment: "Paiement annuel",
    yearlyPaymentDesc: "Économisez en vous engageant pour une année complète",
    save: "Économisez",
    installmentPayment: "Paiement échelonné",
    installmentPaymentDesc: "Possibilité de paiement en plusieurs fois pour les forfaits annuels",
    contactForDetails: "Nous contacter pour plus de détails",
    faqTitle: "Questions fréquentes",
    faqQuestion1: "Comment choisir le forfait qui me convient ?",
    faqAnswer1: "Nos experts sont disponibles pour vous aider à évaluer vos besoins en sécurité et vous recommander le forfait le plus adapté. N'hésitez pas à nous contacter pour une consultation gratuite.",
    faqQuestion2: "Puis-je changer de forfait en cours d'abonnement ?",
    faqAnswer2: "Oui, vous pouvez passer à un forfait supérieur à tout moment. Pour passer à un forfait inférieur, le changement sera effectif à la fin de votre période de facturation en cours.",
    faqQuestion3: "Y a-t-il des frais supplémentaires non inclus dans les prix affichés ?",
    faqAnswer3: "Les prix affichés incluent toutes les fonctionnalités mentionnées. Des frais supplémentaires peuvent s'appliquer uniquement pour des services personnalisés ou des interventions d'urgence hors forfait.",
    faqQuestion4: "Offrez-vous des tarifs préférentiels pour les organisations à but non lucratif ?",
    faqAnswer4: "Oui, nous proposons des remises spéciales pour les associations et organismes à but non lucratif. Contactez-nous pour en savoir plus.",
    readyToSecure: "Prêt à sécuriser votre infrastructure ?",
    notSureWhichPlan: "Pas sûr du forfait qui vous convient ? Nos experts en sécurité sont là pour vous guider",
    contactExperts: "Contacter nos experts",
    monthAbbr: "mois",
    yearAbbr: "an",
    recommended: "Recommandé",
    fromPrice: "à partir de",
    halfDay: "demi-journée",
    intervention: "intervention",
    person: "personne",
    
    // Plan cards related translations
    essentialPlan: "Essentiel",
    essentialAudience: "Pour les très petites entreprises",
    essentialFeature1: "Audit de sécurité initial",
    essentialFeature2: "Protection antivirus basique",
    essentialFeature3: "Sauvegardes mensuelles",
    essentialFeature4: "Support par email",
    essentialFeature5: "Mise à jour trimestrielle",
    chooseEssential: "Choisir Essentiel",
    
    // Removing duplicated entry for standardPlan and adding new entry
    // standardPlan is already defined earlier
    standardAudience: "Pour les PME",
    standardFeature1: "Tout ce qui est inclus dans Essentiel",
    standardFeature2: "Audit de sécurité trimestriel",
    standardFeature3: "Protection avancée des endpoints",
    standardFeature4: "Sauvegardes hebdomadaires",
    standardFeature5: "Support téléphonique 8h-18h",
    standardFeature6: "Formation de base pour les employés",
    chooseStandard: "Choisir Standard",
    
    // Removing duplicated entry for premiumPlan and adding new entry
    // premiumPlan is already defined earlier
    premiumAudience: "Pour les entreprises moyennes et grandes",
    premiumFeature1: "Tout ce qui est inclus dans Standard",
    premiumFeature2: "Audit de sécurité mensuel",
    premiumFeature3: "Protection complète du réseau",
    premiumFeature4: "Sauvegardes quotidiennes",
    premiumFeature5: "Support 24/7 avec temps de réponse garanti",
    premiumFeature6: "Programme complet de formation et sensibilisation",
    choosePremium: "Choisir Premium",
    
    // Service cards related translations
    requestQuote: "Demander un devis",
    basicAuditTitle: "Audit de sécurité basique",
    basicAuditDesc: "Évaluation complète de votre infrastructure IT pour identifier les vulnérabilités et les risques potentiels",
    advancedAuditTitle: "Audit de sécurité avancé",
    advancedAuditDesc: "Analyse approfondie incluant tests de pénétration et scans de vulnérabilité détaillés",
    complianceAuditTitle: "Audit de conformité",
    complianceAuditDesc: "Vérification de la conformité de votre infrastructure avec les réglementations en vigueur (GDPR, etc.)",
    onsiteInterventionTitle: "Intervention sur site",
    onsiteInterventionDesc: "Déplacement d'un technicien pour résoudre des problèmes spécifiques ou mettre en place des solutions",
    emergencyInterventionTitle: "Intervention d'urgence",
    emergencyInterventionDesc: "Réponse rapide en cas d'incident de sécurité avec mobilisation immédiate de nos experts",
    trainingTitle: "Formation et sensibilisation",
    trainingDesc: "Sessions de formation personnalisées pour vos employés sur les bonnes pratiques de cybersécurité",
    
    // Home page specific translations
    simplifiedCybersec: "La cybersécurité simplifiée pour les entreprises marocaines",
    heroSubtitle: "Des solutions de protection informatique adaptées à votre organisation, dans un langage clair et avec un accompagnement personnalisé",
    requestAudit: "Demander un audit gratuit",
    discoverSolutions: "Découvrir nos solutions",
    problemTitle: "Le problème",
    problemText: "La cybersécurité est souvent perçue comme complexe et coûteuse, ce qui laisse de nombreuses entreprises marocaines vulnérables face aux menaces numériques croissantes.",
    solutionTitle: "Notre solution",
    solutionText: "SecureGov rend la cybersécurité accessible avec des solutions adaptées au contexte local, un accompagnement bilingue et des prix adaptés au marché marocain.",
    ourServices: "Nos services",
    exploreAllServices: "Explorer tous nos services",
    securityAuditDesc: "Évaluation approfondie de votre infrastructure pour identifier et corriger les vulnérabilités",
    antivirusProtectionDesc: "Protection complète contre les malwares, virus et autres menaces en ligne",
    secureBackupDesc: "Sauvegarde automatisée et sécurisée de vos données critiques",
    wifiSecurityDesc: "Sécurisation et optimisation de vos réseaux sans fil",
    updatesManagement: "Gestion des mises à jour",
    updatesManagementDesc: "Suivi et déploiement des correctifs de sécurité sur tous vos systèmes",
    trainingAwarenessDesc: "Formation de vos collaborateurs aux bonnes pratiques de cybersécurité",
    whyChooseUs: "Pourquoi nous choisir",
    whyChooseUsDescription: "SecureGov se différencie par son approche locale et adaptée au contexte des entreprises marocaines",
    simplicity: "Simplicité",
    simplicityDesc: "Nous expliquons la cybersécurité dans un langage clair, sans jargon technique inutile",
    localExpertise: "Expertise locale",
    localExpertiseDesc: "Notre équipe comprend les spécificités du marché marocain et les défis particuliers de la région",
    educationalApproach: "Approche pédagogique",
    educationalApproachDesc: "Nous formons vos équipes pour qu'elles deviennent votre première ligne de défense",
    bilingualSupport: "Support bilingue",
    bilingualSupportDesc: "Assistance disponible en français et en arabe pour une communication optimale",
    adaptedPricing: "Tarification adaptée",
    adaptedPricingDesc: "Des prix en adéquation avec le marché marocain et la taille de votre entreprise",
    complianceReg: "Conformité réglementaire",
    complianceRegDesc: "Solutions conformes aux réglementations marocaines et internationales en matière de protection des données",
    satisfactionRate: "Taux de satisfaction client",
    protectedCompanies: "Entreprises protégées",
    majorIncident: "Incident majeur depuis 5 ans",
    testimonialsSectionTitle: "Ce que nos clients disent",
    testimonialsDescription: "Découvrez les retours d'expérience de nos clients qui nous font confiance pour leur sécurité informatique",
    // Missing translations for CallToActionSection
    name: "Nom",
    audit: "Demander un audit gratuit",
    howHelp: "Comment pouvons-nous vous aider?",
    
    // Adding missing translations for Resources page
    cybersecResources: "Ressources en cybersécurité",
    cybersecResourcesDescription: "Des guides, des documents et des études de cas pour vous aider à protéger votre entreprise",
    cantFind: "Vous ne trouvez pas ce que vous cherchez ?",
    cantFindDesc: "N'hésitez pas à nous contacter pour des ressources personnalisées ou des conseils spécifiques à votre situation.",
  },
  ar: {
    securitySolutions: "حلول أمنية للجميع",
    services: "خدمات",
    securityAudit: "تدقيق أمني",
    antivirusProtection: "حماية من الفيروسات",
    secureBackup: "نسخ احتياطي آمن",
    wifiSecurity: "أمن شبكة الواي فاي",
    trainingAwareness: "التدريب والتوعية",
    resources: "مصادر",
    guidesAndDocs: "أدلة ووثائق",
    caseStudies: "دراسات الحالة",
    contact: "اتصل بنا",
    legalMentions: "البيانات القانونية",
    privacyPolicy: "سياسة الخصوصية",
    copyright: "جميع الحقوق محفوظة",
    home: "الرئيسية",
    pricing: "التسعير",
    aboutUs: "من نحن",
    whyUs: "لماذا نحن",
    ourValues: "قيمنا",
    ourMission: "مهمتنا",
    ourVision: "رؤيتنا",
    contactUs: "اتصل بنا",
    getInTouch: "ابق على اتصال!",
    fullName: "الاسم الكامل",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    message: "الرسالة",
    sendMessage: "إرسال الرسالة",
    enterFullName: "أدخل اسمك الكامل",
    enterValidEmail: "أدخل عنوان بريد إلكتروني صالح",
    enterPhoneNumber: "أدخل رقم هاتفك",
    writeYourMessage: "اكتب رسالتك",
    successMessage: "تم إرسال رسالتك بنجاح!",
    errorMessage: "حدث خطأ. يرجى المحاولة مرة أخرى.",
    latestNews: "آخر الأخبار",
    readMore: "اقرأ المزيد",
    stayUpdated: "ابق على اطلاع",
    subscribeToNewsletter: "اشترك في نشرتنا الإخبارية",
    enterYourEmail: "أدخل بريدك الإلكتروني",
    subscribe: "اشترك",
    subscribeSuccess: "شكرا لك على الاشتراك في نشرتنا الإخبارية!",
    subscribeError: "غير قادر على الاشتراك. يرجى المحاولة مرة أخرى.",
    highQualityServices: "خدمات عالية الجودة",
    customerSatisfaction: "رضا العملاء",
    innovativeSolutions: "حلول مبتكرة",
    expertTeam: "فريق خبراء",
    yearsOfExperience: "سنوات الخبرة",
    happyClients: "عملاء سعداء",
    projectsCompleted: "المشاريع المنجزة",
    ourPricing: "أسعارنا",
    basicPlan: "الخطة الأساسية",
    standardPlan: "الخطة القياسية",
    premiumPlan: "الخطة المميزة",
    monthly: "شهريا",
    annual: "سنويا",
    choosePlan: "اختر هذه الخطة",
    allRightsReserved: "جميع الحقوق محفوظة",
    comprehensiveSecurity: "أمان شامل لشركتك",
    dataProtection: "حماية البيانات",
    networkSecurity: "أمن الشبكات",
    endpointSecurity: "أمن الأجهزة الطرفية",
    cloudSecurity: "أمن السحابة",
    incidentResponse: "الاستجابة للحوادث",
    managedSecurityServices: "خدمات الأمن المدارة",
    vulnerabilityAssessment: "تقييم الثغرات الأمنية",
    penetrationTesting: "اختبار الاختراق",
    securityConsulting: "استشارات أمنية",
    complianceServices: "خدمات الامتثال",
    digitalForensics: "الأدلة الجنائية الرقمية",
    securityTraining: "التدريب الأمني",
    awarenessPrograms: "برامج التوعية",
    phishingSimulations: "محاكاة التصيد الاحتيالي",
    customTraining: "تدريب مخصص",
    ourClients: "عملائنا",
    testimonials: "شهادات",
    whatPeopleSay: "ماذا يقول الناس",
    submit: "إرسال",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    company: "الشركة",
    function: "الوظيفة",
    enterFirstName: "أدخل اسمك الأول",
    enterLastName: "أدخل اسم عائلتك",
    enterCompanyName: "أدخل اسم شركتك",
    enterYourFunction: "أدخل وظيفتك",
    selectLanguage: "اختر اللغة",
    french: "الفرنسية",
    arabic: "العربية",
    english: "الإنجليزية",
    contactFormTitle: "اتصل بنا للحصول على استشارة مجانية",
    contactFormDescription: "املأ النموذج أدناه وسنتصل بك في أقرب وقت ممكن.",
    address: "العنوان",
    phoneNumbers: "أرقام الهاتف",
    emailAddress: "عنوان البريد الإلكتروني",
    followUs: "تابعنا",
    ourOffices: "مكاتبنا",
    casablancaOffice: "الدار البيضاء",
    rabatOffice: "الرباط",
    marrakechOffice: "مراكش",
    ourPartners: "شركاؤنا",
    strategicAlliances: "تحالفات استراتيجية",
    technologyPartners: "شركاء التكنولوجيا",
    industryAssociations: "الجمعيات الصناعية",
    ourBlog: "مدونتنا",
    recentArticles: "المقالات الحديثة",
    whyChoose: "لماذا تختارنا",
    
    // Pricing page specific translations
    pricingTitle: "باقاتنا وأسعارنا",
    pricingDescription: "حلول أمنية مناسبة لجميع الميزانيات والاحتياجات الخاصة",
    subscriptionPlansTitle: "خطط الاشتراك",
    servicesTitle: "خدمات مخصصة",
    servicesDescription: "هل تحتاج إلى تدخل أو تحليل مخصص؟ اكتشف خدماتنا حسب الطلب",
    paymentOptionsTitle: "خيارات الدفع",
    monthlyPayment: "الدفع الشهري",
    monthlyPaymentDesc: "مرونة قصوى، بدون التزام مدة",
    standardRate: "السعر القياسي",
    yearlyPayment: "الدفع السنوي",
    yearlyPaymentDesc: "وفر بالالتزام لمدة سنة كاملة",
    save: "وفر",
    installmentPayment: "الدفع بالتقسيط",
    installmentPaymentDesc: "إمكانية الدفع على أقساط للخطط السنوية",
    contactForDetails: "اتصل بنا للحصول على مزيد من التفاصيل",
    faqTitle: "الأسئلة الشائعة",
    faqQuestion1: "كيف أختار الخطة المناسبة لي؟",
    faqAnswer1: "خبراؤنا متاحون لمساعدتك في تقييم احتياجاتك الأمنية وتوصية الخطة الأنسب لك. لا تتردد في الاتصال بنا للحصول على استشارة مجانية.",
    faqQuestion2: "هل يمكنني تغيير الخطة أثناء الاشتراك؟",
    faqAnswer2: "نعم، يمكنك الترقية إلى خطة أعلى في أي وقت. للانتقال إلى خطة أقل، سيصبح التغيير ساريًا في نهاية فترة الفوترة الحالية.",
    faqQuestion3: "هل هناك رسوم إضافية غير مشمولة في الأسعار المعروضة؟",
    faqAnswer3: "تشمل الأسعار المعروضة جميع الميزات المذكورة. قد تنطبق رسوم إضافية فقط على الخدمات المخصصة أو التدخلات الطارئة خارج الخطة.",
    faqQuestion4: "هل تقدمون أسعارًا تفضيلية للمؤسسات غير الربحية؟",
    faqAnswer4: "نعم، نقدم خصومات خاصة للجمعيات والمنظمات غير الربحية. اتصل بنا لمعرفة المزيد.",
    readyToSecure: "مستعد لتأمين بنيتك التحتية؟",
    notSureWhichPlan: "غير متأكد من الخطة المناسبة لك؟ خبراء الأمن لدينا هنا لإرشادك",
    contactExperts: "تواصل مع خبرائنا",
    monthAbbr: "شهر",
    yearAbbr: "سنة",
    recommended: "موصى به",
    fromPrice: "ابتداء من",
    halfDay: "نصف يوم",
    intervention: "تدخل",
    person: "شخص",
    
    // Plan cards related translations
    essentialPlan: "أساسي",
    essentialAudience: "للشركات الصغيرة جدًا",
    essentialFeature1: "تدقيق أمني أولي",
    essentialFeature2: "حماية أساسية من الفيروسات",
    essentialFeature3: "نسخ احتياطي شهري",
    essentialFeature4: "دعم عبر البريد الإلكتروني",
    essentialFeature5: "تحديث ربع سنوي",
    chooseEssential: "اختر الخطة الأساسية",
    
    // Removing duplicated entry for standardPlan and adding new entry
    // standardPlan is already defined earlier
    standardAudience: "للشركات الصغيرة والمتوسطة",
    standardFeature1: "كل ما هو مشمول في الخطة الأساسية",
    standardFeature2: "تدقيق أمني ربع سنوي",
    standardFeature3: "حماية متقدمة للأجهزة الطرفية",
    standardFeature4: "نسخ احتياطي أسبوعي",
    standardFeature5: "دعم هاتفي من 8 صباحًا حتى 6 مساءً",
    standardFeature6: "تدريب أساسي للموظفين",
    chooseStandard: "اختر الخطة القياسية",
    
    // Removing duplicated entry for premiumPlan and adding new entry
    // premiumPlan is already defined earlier
    premiumAudience: "للشركات المتوسطة والكبيرة",
    premiumFeature1: "كل ما هو مشمول في الخطة القياسية",
    premiumFeature2: "تدقيق أمني شهري",
    premiumFeature3: "حماية شبكة كاملة",
    premiumFeature4: "نسخ احتياطي يومي",
    premiumFeature5: "دعم على مدار الساعة طوال أيام الأسبوع مع ضمان وقت الاستجابة",
    premiumFeature6: "برنامج شامل للتدريب والتوعية",
    choosePremium: "اختر الخطة المتميزة",
    
    // Service cards related translations
    requestQuote: "طلب عرض سعر",
    basicAuditTitle: "تدقيق أمني أساسي",
    basicAuditDesc: "تقييم شامل للبنية التحتية لتكنولوجيا المعلومات لتحديد نقاط الضعف والمخاطر المحتملة",
    advancedAuditTitle: "تدقيق أمني متقدم",
    advancedAuditDesc: "تحليل متعمق يشمل اختبارات الاختراق وفحص نقاط الضعف المفصلة",
    complianceAuditTitle: "تدقيق الامتثال",
    complianceAuditDesc: "التحقق من امتثال البنية التحتية للوائح المعمول بها (GDPR، إلخ)",
    onsiteInterventionTitle: "تدخل في الموقع",
    onsiteInterventionDesc: "إرسال فني لحل مشكلات محددة أو تنفيذ حلول",
    emergencyInterventionTitle: "تدخل طارئ",
    emergencyInterventionDesc: "استجابة سريعة في حالة حوادث الأمن مع تعبئة فورية لخبرائنا",
    trainingTitle: "تدريب وتوعية",
    trainingDesc: "جلسات تدريبية مخصصة لموظفيك حول أفضل ممارسات الأمن السيبراني",

    // Home page specific translations
    simplifiedCybersec: "الأمن السيبراني المبسط للشركات المغربية",
    heroSubtitle: "حلول حماية تكنولوجيا المعلومات مكيفة لمؤسستك، بلغة واضحة ودعم مخصص",
    requestAudit: "طلب تدقيق مجاني",
    discoverSolutions: "اكتشف حلولنا",
    problemTitle: "المشكلة",
    problemText: "غالبًا ما يُنظر إلى الأمن السيبراني على أنه معقد ومكلف، مما يترك العديد من الشركات المغربية عرضة للتهديدات الرقمية المتزايدة.",
    solutionTitle: "حلنا",
    solutionText: "SecureGov تجعل الأمن السيبراني في متناول الجميع مع حلول مكيفة للسياق المحلي، ودعم ثنائي اللغة، وأسعار مناسبة للسوق المغربية.",
    ourServices: "خدماتنا",
    exploreAllServices: "استكشاف جميع خدماتنا",
    securityAuditDesc: "تقييم شامل للبنية التحتية لديك لتحديد نقاط الضعف وتصحيحها",
    antivirusProtectionDesc: "حماية كاملة من البرامج الضارة والفيروسات والتهديدات الأخرى عبر الإنترنت",
    secureBackupDesc: "نسخ احتياطي آلي وآمن لبياناتك الحرجة",
    wifiSecurityDesc: "تأمين وتحسين شبكاتك اللاسلكية",
    updatesManagement: "إدارة التحديثات",
    updatesManagementDesc: "متابعة ونشر تحديثات الأمان على جميع أنظمتك",
    trainingAwarenessDesc: "تدريب موظفيك على أفضل ممارسات الأمن السيبراني",
    whyChooseUs: "لماذا تختارنا",
    whyChooseUsDescription: "تتميز SecureGov بنهجها المحلي والمكيف لسياق الشركات المغربية",
    simplicity: "البساطة",
    simplicityDesc: "نشرح الأمن السيبراني بلغة واضحة، دون مصطلحات تقنية غير ضرورية",
    localExpertise: "خبرة محلية",
    localExpertiseDesc: "فريقنا يفهم خصوصيات السوق المغربية والتحديات الخاصة بالمنطقة",
    educationalApproach: "النهج التعليمي",
    educationalApproachDesc: "نقوم بتدريب فرقك لتصبح خط الدفاع الأول لديك",
    bilingualSupport: "دعم ثنائي اللغة",
    bilingualSupportDesc: "المساعدة متاحة باللغتين الفرنسية والعربية للتواصل الأمثل",
    adaptedPricing: "تسعير مكيف",
    adaptedPricingDesc: "أسعار تتماشى مع السوق المغربية وحجم شركتك",
    complianceReg: "الامتثال التنظيمي",
    complianceRegDesc: "حلول متوافقة مع اللوائح المغربية والدولية لحماية البيانات",
    satisfactionRate: "معدل رضا العملاء",
    protectedCompanies: "شركة محمية",
    majorIncident: "حادث رئيسي منذ 5 سنوات",
    testimonialsSectionTitle: "ما يقوله عملاؤنا",
    testimonialsDescription: "اكتشف تجارب عملائنا الذين يثقون بنا لأمن تكنولوجيا المعلومات لديهم",
    // Missing translations for CallToActionSection
    name: "اسم",
    audit: "طلب تدقيق أمني مجاني",
    howHelp: "كيف يمكننا مساعدتك؟",
    
    // Adding missing translations for Resources page
    cybersecResources: "موارد الأمن السيبراني",
    cybersecResourcesDescription: "أدلة ووثائق ودراسات حالة لمساعدتك في حماية عملك",
    cantFind: "لم تجد ما تبحث عنه؟",
    cantFindDesc: "لا تتردد في الاتصال بنا للحصول على موارد مخصصة أو نصائح خاصة بوضعك.",
  },
};

export const LanguageContext = createContext<{
  language: Language;
  setLanguage: (language: Language) => void;
}>({
  language: "fr",
  setLanguage: () => console.warn("setLanguage function is not overridden"),
});

export const useLanguage = () => useContext(LanguageContext);

export const getTranslation = (
  language: Language,
  key: keyof Translation
): string => {
  return translations[language][key] || `Missing translation for ${key} in ${language}`;
};

// Add the LanguageSelector component
const LanguageSelector = () => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    return (savedLanguage && (savedLanguage === "fr" || savedLanguage === "ar")) ? savedLanguage : "fr";
  });

  const toggleLanguage = () => {
    const newLanguage = language === "fr" ? "ar" : "fr";
    localStorage.setItem("language", newLanguage);
    setLanguage(newLanguage);
    
    // Dispatch a custom event to notify other components of the language change
    const event = new CustomEvent("languageChange", {
      detail: { language: newLanguage }
    });
    document.dispatchEvent(event);
  };
  
  return (
    <button 
      onClick={toggleLanguage}
      className="flex items-center text-gray-dark hover:text-blue-royal transition-colors"
      aria-label={getTranslation(language, "selectLanguage")}
    >
      <Globe size={18} className="mr-1" />
      <span className="font-medium">
        {language === "fr" ? "FR" : "AR"}
      </span>
    </button>
  );
};

export default LanguageSelector;
